### ISSUE TITLE
APIResponse<GenericResponse>.Payload.PlayerProgression.LootboxProb should be AlphaPackProb

### ISSUE THREAD

**Issue by alexjshepler** [Cenngo/R6Stats-Sharp#4]
I know this isn't the biggest issue just to be more consistent with rainbow six terminology

**Comment by Cenngo** [comment]
LootboxProb is the name of the property in the R6Stats API and I didnt change the name with the intention of keeping this client consistent with R6stats teams reference client, in case they decide to create a documentation in the future it should be easier to cross reference. I think the property's xml documentation is clear enough. But it can be changed in the future if necessary

**Comment by alexjshepler** [comment]
Alright, thanks
