### ISSUE TITLE
var rankedStats = await client.GetSeasonalStats(username, platform); doesn't work for me

### ISSUE THREAD

**Issue by alexjshepler** [Cenngo/R6Stats-Sharp#5]
I'm trying to do `var rankedStats = await client.GetSeasonalStats(username, platform);` but its not working. I do that but for the `client.GetGenericStats(username,platform);` and it works fine. I get all of the data that I need. but when I do that, the function that I'm in just exits. I get the error `Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll` How can I change this?

**Comment by Cenngo** [comment]
yeah i am aware of that problem. It should be fixed in the final build of the package.

**Comment by alexjshepler** [comment]
Thank you, do you have an estimated time of when it should be fixed?

**Comment by Cenngo** [comment]
i already updated the package several days ago, you just need to update

**Comment by alexjshepler** [comment]
Alright, thanks
